// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEGHwC9yS_kCEuka6S7gpi_fNHUJQwMW4',
    appId: '1:34463995348:web:8138da59b4905778193241',
    messagingSenderId: '34463995348',
    projectId: 'sekolahapp-a7f85',
    authDomain: 'sekolahapp-a7f85.firebaseapp.com',
    storageBucket: 'sekolahapp-a7f85.firebasestorage.app',
    measurementId: 'G-526YQD8W3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByuF7SsYkkgQQSgcwVf2uYyhLYwU84Aio',
    appId: '1:34463995348:android:6c7f08f5395a9eb2193241',
    messagingSenderId: '34463995348',
    projectId: 'sekolahapp-a7f85',
    storageBucket: 'sekolahapp-a7f85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsxlZ37h2j6cEHp4uP_W-VZjDG04I1VMU',
    appId: '1:34463995348:ios:0dc7336d8f8f42ab193241',
    messagingSenderId: '34463995348',
    projectId: 'sekolahapp-a7f85',
    storageBucket: 'sekolahapp-a7f85.firebasestorage.app',
    iosBundleId: 'com.example.praktikumMobileDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsxlZ37h2j6cEHp4uP_W-VZjDG04I1VMU',
    appId: '1:34463995348:ios:0dc7336d8f8f42ab193241',
    messagingSenderId: '34463995348',
    projectId: 'sekolahapp-a7f85',
    storageBucket: 'sekolahapp-a7f85.firebasestorage.app',
    iosBundleId: 'com.example.praktikumMobileDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEGHwC9yS_kCEuka6S7gpi_fNHUJQwMW4',
    appId: '1:34463995348:web:dd0b382c6adee414193241',
    messagingSenderId: '34463995348',
    projectId: 'sekolahapp-a7f85',
    authDomain: 'sekolahapp-a7f85.firebaseapp.com',
    storageBucket: 'sekolahapp-a7f85.firebasestorage.app',
    measurementId: 'G-B19ZB2TCNW',
  );
}
